$script = <<-SCRIPT
echo hello world....
mkdir bin
SCRIPT

Vagrant.configure("2") do |config|

    config.vm.define "server1" do |ser1|    
        ser1.vm.provider "virtualbox" do |vb_ser1|
            vb_ser1.cpus = 2
            vb_ser1.memory = "4096"
        end

        ser1.vm.box = 'ubuntu/trusty64'
        ser1.vm.hostname = "server-1-test"
        ser1.vm.network  "private_network", ip: "192.168.1.11" 
    end
    
    config.vm.define "server2" do |ser2|
        ser2.vm.provider "virtualbox" do |vb_ser2|
            vb_ser2.cpus = 2
            vb_ser2.memory = "4096"
        end

        ser2.vm.box = "ubuntu/trusty64"
        ser2.vm.hostname = "server2-test"
        ser2.vm.network  "private_network", ip: "192.168.1.12" 
    end

    config.vm.provision "shell", inline: $script

end
