# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "192.168.10.12"
    config.vm.hostname = "worker2.lab"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "worker2.lab"
        vb.cpus = 2
        vb.memory = "2048"
    end

    config.vm.provision "shell", path: "./../install-docker-k8s.sh"

    config.vm.provision "shell", inline: <<-SHELL
        #Change the password os root
        echo "123" | passwd --stdin root
        sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        systemctl reload sshd
        #Import IP to /etc/hosts file
        cat >>/etc/hosts<<EOF
        192.168.10.10 master.lab
        192.168.10.11 worker1.lab
        192.168.10.12 worker2.lab
    SHELL
end